# Generated by Django 5.0.6 on 2024-09-15 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0002_rename_user_transaction_account_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='transaction_type',
            field=models.IntegerField(choices=[(1, 'Deposite'), (2, 'Withdrawal'), (3, 'Load'), (4, 'Load paid'), (5, 'Transfer Out'), (6, 'Transfer In')], null=True),
        ),
    ]
